### ISSUE TITLE
Fix donate payment system

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#17]
This includes:
- [x] Donate page with options for monthly vs  one time
- [x] Sponsorships
- [x] Invest in a good cause with pre-filled amount (9 of them)

**Comment by kelseyfriedman** [comment]
Hi @JuliaDickey

This is something that you might want to discuss with Ashley, but I wanted to put this out there. I clicked on "pay with card" and on both mobile and desktop a modal popped up that had almost no information on it about the payment system. As someone who has never heard of Stripe, I would be very reluctant to put in my credit card number into something that vague. I think we need to add some kind of explanation on the payment pages that says what Stripe is, confirms that it's safe, makes people feel secure... somehow. Otherwise we may lose donations. With PayPal most people have an account so they feel safe using it (or at least know of PP) whereas we are asking people to blindly put in a credit card number with no promise that their data is safe. 

Let me know what you think? Maybe you can check and see what other pages that use Stripe are doing to make their users feel secure about the relatively new service. 

Thanks

**Comment by JuliaDickey** [comment]
Good point. Hmmm. It has a big green lock on the top showing it's a secure payment method. We can also add a Stripe secure payment badge, I believe. I'll chat with Matt about it. To its credit, Stripe has been around for seven years and is backed by Elon Musk. It also has an A+ rating with the Better Bus Bureau. It's not a risky payment option.

**Comment by kelseyfriedman** [comment]
I totally believe that it's a great service and not actually risky, but it's just not as well known, so people will be wary, myself included. I don't see a lock or anything that indicates it's secure? It's just a form with no info on it. Here's what I see
![screen shot 2017-03-15 at 3 55 27 pm](https://cloud.githubusercontent.com/assets/3065594/23949408/20218b1c-0998-11e7-8f5a-17d15fc283e8.png)

I think a badge, or a link to their site, or something would be helpful. Just like PayPal very clearly shows their logo and makes it obvious where your money is going, we need something similar.

**Comment by JuliaDickey** [comment]
Made good progress on this today. I'll finish it tomorrow along with maps! Yeah buddy!

**Comment by kelseyfriedman** [comment]
Will you look at this on an iPhone when you are done? The custom amount field is funky and a lot of the buttons aren't aligned

**Comment by JuliaDickey** [comment]
A few things to tweak on sponsor and invest payment mobile pages, but the donation page is fixed for mobile and tablet. Payments are good to go. I just need to hide the custom donation option for more than just one-time payment. 

In the morning I'll remove the monthly and yearly options for Invest in a Cause.

**Comment by JuliaDickey** [comment]
All updated with a Stripe badge on the payment page that links to their site. I added Red Sweater Project to the modal as well. 

I tweaked the Invest payment page, so if the amount is greater than $200, only the one-time option comes up. If it's less, there is a one-time or monthly option. 

I'm sending you the password for the payment account so you can test payments. Everything is updated for mobile, and the monthly and yearly options disappear if the user selects a custom amount.

**Comment by kelseyfriedman** [comment]
- [ ] I thought we agreed to have one-time only for all the invest in a cause regardless of the dollar amount? I think they should be consistent.... but I'm not gonna fight this one too hard, it's just what we talked about on the call. 
- [ ] All the custom messages are missing from the Invest Cause pages
- [ ] I see the badge on the payment page - any way to add it to the actual modal? That's where the credit card info is inputted and I think that would help to put something on that page so when they are entering it they know. 
- [ ] I'm not exactly clear on how to test with a test account? It just asked for a credit card? There's no where to sign in? I'd actually prefer you to test this fully with Ashley in person if that's okay. Do you have to have a stripe account to pay? It's asking for an email but no log in?

**Comment by JuliaDickey** [comment]
-There's a comment about this above. I can make it a one-time payment, but it seemed like a great way to get people to sign up for ongoing donations if the value is less than 200. I wrote a comment about this above your last comment. If you'd rather it just be one-time across the board, that's cool. Doesn't really matter to me. 

-I added the custom messages to the Invest Cause pages. Let me know if this works for you.

-You can test the payment account by entering any email or test@account.com, use the credit card number 4242 4242 4242 4242, any future expiration date, and any 3 numbers for the CVC. It will take you to a summary page of your donation, and your payment will show up in our stripe account. I sent you the credentials to log in. To to Red Sweater Project in the dropdown from the top left, then click "Subscriptions" in the left nav to view ongoing payments, and "Purchases" to see one-time payments. There's no login. It's just a credit card payment system. I also set up a receipt email that will trigger when we go live. You can have it send a test email from the Stripe portal. I've done probably a few hundred test payments at this point. 

-I'll see if I can add the badge to the modal. I worked on this for a while yesterday. There should be a way to do this.

**Comment by JuliaDickey** [comment]
I couldn't find a way to add the badge to the modal, but I added the RSP logo, and some details about the payment. It doesn't let you edit the modal directly for security. I can keep trying. At least the additional info feels like less of a disconnect than it did before.

**Comment by kelseyfriedman** [comment]
I saw your comment before, I was just letting you know this isn't what we had agreed on before, which was that all causes would be a one time donation. But again, I'm okay with it if you all like it better this way. Maybe confirm it with Ashley when you go through the donations since this isn't how she originally wanted it?

I do think we need to change one other thing on Invest in Causes. It says "Suggested gift" but when you go to the page, you don't have a choice to change the amount. I think if we say "Suggested" it needs to have the option for custom amounts - or we change the language from "suggested." It's not really a suggestion if they don't have a choice. 

Custom messages look great. 

I'm okay with the modal as is for now. Other things to do. Thanks for working on it. 

I tested a one-time payment for a cause and it worked. I couldn't test Sponsor or Donate because I don't have the address associated with the credit card. I see the payments you tested in the system though so I'm going to call this good and let you and Ashley test them together as final sign off on these. 

Can you make sure the students that were sponsored in your tests end up back on the site before Ashley looks or she'll wonder why there are only 5. Thanks!

**Comment by JuliaDickey** [comment]
Removed 'Suggested' from Invest in a Good Cause. 

You can test sponsor and donate by adding any address as long as the card number is 4242...

I removed the sponsored status from the students so Ashley doesn't worry :)

**Comment by JuliaDickey** [comment]
- [ ] Asking Ashley and Ada about Invest payment options (monthly vs one-time)

**Comment by kelseyfriedman** [comment]
I'm still seeing the word suggested? https://intense-spire-56347.herokuapp.com/goodcauses

What did Ashley decide about monthly vs one time?

**Comment by JuliaDickey** [comment]
She wants to keep the monthly option for values under 200.

**Comment by kelseyfriedman** [comment]
Sounds good. 

Can we remove all the extra padding between the text and dollar amount? Now that we removed "Suggested gift" it's quite spacey

**Comment by JuliaDickey** [comment]
Sure thing. 

- [ ]  Can we edit the Professional Development Training copy just by a line? The end could say "opportunities like computer classes, internships, and peer tutoring." That would tighten it up since that line is longer than the others.

**Comment by kelseyfriedman** [comment]
Definitely, please do!

**Comment by JuliaDickey** [comment]
Done!
