### ISSUE TITLE
Confirm Google Maps API works after next push

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#18]

**Comment by JuliaDickey** [comment]
The volunteer map is up with all Volunteer cities added. I'll add the school location map tomorrow morning.

**Comment by kelseyfriedman** [comment]
This is awesome! I wonder if instead of saying "over 67 cities" we should just say "Our volunteers have come from 11 countries around the world."

I find over 67 a little strange - like why don't we know the exact number? 

Also going to leave this open until the Schools Map is done so we can QA.

**Comment by JuliaDickey** [comment]
That line is updated, and the School map is in as well.
