### ISSUE TITLE
Update hover state on Nav items

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#19]
- [x] From Julia: 
The donate button styling is new. I will be updating the hover state
- [x] Ashley also noticed that on all the other hovers, the link is only active if you click the actual word rather than the whole bar that appears. Is it possible to make the whole element a link so you don't have to click the word? 
- [x] Lastly, on the three nav items with drop downs, the main Nav item is still clickable. On desktop that shouldn't be the case. It makes it feel like it's broken because when you click it "loads" something but then doesn't go anywhere. It should just be a hover that opens a menu but isn't an active link.

**Comment by JuliaDickey** [comment]
Great feedback on the links. Updated.

**Comment by kelseyfriedman** [comment]
I unchecked the box on the third item in my list. This is still happening. When I click on "Who We Are" it closes the menu and reloads the page. It should just be a hover rather than an active link. Is that possible?
