### ISSUE TITLE
Update The School formatting

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#20]
From Julia:
The School formatting isn't done yet. I'm on it.

**Comment by kelseyfriedman** [comment]
- [ ] On mobile, can Prepared for Success section drop down to a single column instead of two? The two columns are quite narrow and difficult to read on a small screen. Also, the right column is much longer, leaving a lot of white space on the left. 
- [ ] On mobile, Hands-On Learning section: the header and intro graph are aligned left but the photos are centered and it's causing the intro to be pushed up against the side of the screen. 
![img_4904](https://cloud.githubusercontent.com/assets/3065594/23352196/d8ae5c24-fcd6-11e6-995b-e5e7ec19fe38.PNG)

**Comment by JuliaDickey** [comment]
I went through the site to fix all padding on mobile. I made some changes last week that threw it off.
