### ISSUE TITLE
Fix Events Add to Calendar widget

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#22]

**Comment by JuliaDickey** [comment]
Fixed it, and added timezones.

**Comment by kelseyfriedman** [comment]
Yes! This looks great. The only thing I wonder is about using the 24 hour clock instead of AM/PM. I guess since we have a global audience it's okay, but it's mostly Americans who will use the site. I'm not sure. Thoughts?

**Comment by JuliaDickey** [comment]
Updated this to a 12 hour AM/PM clock. It looks nicer anyway :)
