### ISSUE TITLE
Tighten up text on Sponsor page

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#23]
- [x] In the last code push this page got really spaced out and the main text seems a lot bigger than on other pages. This is pushing the sponsor and invest info really far below the fold. Can we tighten this up so it's consistent with the other pages and the important stuff (the pictures and donate buttons) are closer to the top? 
- [x] Can you also please update the dollar amount in the text to say instead of USD $125 per month or USD $1,500 a year

**Comment by JuliaDickey** [comment]
Cool. Fixed it. I added a link to student bios, but I don't have them so I put a static link to a job post. Could I get those from you?

**Comment by kelseyfriedman** [comment]
Do you mean the profiles? Ashley emailed them to you. They are going to have to be uploaded on the site. They don't live anywhere else.

**Comment by JuliaDickey** [comment]
Yup. They're there. Found them in my email
