### ISSUE TITLE
Add Sarah Ford photo

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#26]
Assigning this to myself until Ashley provides it so I can keep on her. Will assign to you when we get it.

**Comment by kelseyfriedman** [comment]
Okay we had to pull photos from Facebook because she doesn't have photos? 

They are all bad but please choose whichever one looks least bad. Pole! 
![sarah ford bio photo](https://cloud.githubusercontent.com/assets/3065594/23214928/8cd5ce3a-f921-11e6-9a13-f9628ee54dd3.jpeg)
![sarah ford bio photo2](https://cloud.githubusercontent.com/assets/3065594/23214929/8cd8b19a-f921-11e6-81fe-73866b7f7793.jpeg)
![sarah ford bio photo3](https://cloud.githubusercontent.com/assets/3065594/23214930/8cdbf0d0-f921-11e6-847f-06ff48b6fabf.jpeg)

**Comment by JuliaDickey** [comment]
Cool. Using the second one.
