### ISSUE TITLE
Broken layout on Schools page

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#32]
ABOUT TANZANIA, EAST AFRICA
- [x] the map is no longer floating right of the text like it did, it's kind of floating below. I know the API is broken so I'm assuming that's why I don't see the map, but the layout is no longer side by side. 
- [x] I cannot see the link color on this blue background.

**Comment by kelseyfriedman** [comment]
Looks great! Good job.

The leadership and teamwork photo loaded really slowly. Is it resized?

**Comment by JuliaDickey** [comment]
It was 1mb. I resized it so it should be much faster now.

**Comment by kelseyfriedman** [comment]
Yahoo!! Done

**Comment by kelseyfriedman** [comment]
Oops wrong bug. I went to write that on the Our Story bug :)
