### ISSUE TITLE
Grid layout broken on Get Creative

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#34]
This grid is supposed to be 3 across but it's now splitting it 2 and then 1 below it.

**Comment by kelseyfriedman** [comment]
The image on the left is taller than the other two. Please make them all equal so the grid is uniform

**Comment by kelseyfriedman** [comment]
The  two images on the right are broken on my screen. Can you see them @JuliaDickey?

**Comment by JuliaDickey** [comment]
Ooops! I was clearing out unused images from the project, and accidentally pulled a few that we're actually using. Fixed it!
