### ISSUE TITLE
Add privacy policy content

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#36]
Kelsey needs to get from Jordan - in progress

**Comment by kelseyfriedman** [comment]
Here is the privacy policy content 
[RSP Privacy Policy v2.docx](https://github.com/JuliaDickey/Red-Sweater-Project-Rails/files/779246/RSP.Privacy.Policy.v2.docx)

**Comment by JuliaDickey** [comment]
I added a modal that pops up when the user clicks the privacy link.

**Comment by kelseyfriedman** [comment]
Perfect!
