### ISSUE TITLE
Resize Blog Images

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#37]
This is for me to do so we can link it all up once the blog is done

**Comment by kelseyfriedman** [comment]
waiting on issue #4 to be completed

**Comment by JuliaDickey** [comment]
I've added all of the posts you sent over.

**Comment by kelseyfriedman** [comment]
Thanks! Did you reduce the image size before adding them? They were all pretty huge images and they are taking a really long time to load. If not, I can go through and resize them and add them back in. I went to the admin dashboard to try to figure out how to do that but there doesn't seem to be a way to edit images? 

Also, if I delete the images you added, will it delete them from the server? I don't want to take up a bunch of space but adding more images on top of those.

**Comment by JuliaDickey** [comment]
If you could do this it would be great. I don't have Photoshop anymore. If you hit 'Update' then 'Browse' on gallery photos or main image it will replace the existing photos with whatever you select. The gallery photos supports multiple image selection (up to 6), so put the new images in a folder and you can select them all in one go. Deleting or Updating images removes the old ones from the server.

**Comment by kelseyfriedman** [comment]
I'll work on this tomorrow

**Comment by kelseyfriedman** [comment]
@JuliaDickey when I click Edit from the admin dashboard the pages are broken. I'll get the images resized today so they are ready, but can you prioritize this so I can update the blog ASAP? 

Thanks

**Comment by kelseyfriedman** [comment]
This is fixed
