### ISSUE TITLE
Update Jobs and add PDFs

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#39]
- [ ] Positions should only list title, location and term on the main page. The title should be a link to the PDF which has all the other info. This should make your life much easier.

**Comment by JuliaDickey** [comment]
Did you send me the jobs pdfs? Should I pull these from the other site?

**Comment by kelseyfriedman** [comment]
Please pull from site

**Comment by kelseyfriedman** [comment]
@JuliaDickey  FYI, I'm checking with Ashley to see if she intends to update any of these since some are now past the date (Feb 2017). Maybe save this bug for the end so I can send updated PDFs if needed?

I'm assuming when we have the admin dashboard all working, I'll be able to edit the dates and update the PDFs myself right? 

I'm assigning this to myself to confirm that the positions are correct with Ashley

**Comment by kelseyfriedman** [comment]
Okay Ashley says to go with what's on the current site and we will update them accordingly once we have full access to the admin dashboard. Which means you just need to add the PDFs and we're done with this page. 

Thanks

**Comment by JuliaDickey** [comment]
Cool. I pulled the PDFs from the old site, and updated the admin panel, so you can Create/Update/Delete/List these from there.

**Comment by JuliaDickey** [comment]
Cool, I pulled in the PDFs from the old site, added them as links that open in a new tab. You can also update these in the admin portal now.

**Comment by kelseyfriedman** [comment]
Looks great!
