### ISSUE TITLE
add Student Sponsor PDFS

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#40]
Names and pictures should link to the PDF profile

**Comment by JuliaDickey** [comment]
Do I have these?

**Comment by kelseyfriedman** [comment]
This page is broken and I can't check this. Please look at this error 

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by kelseyfriedman** [comment]
Looks good but the text link to Learn more about me is missing on mobile

**Comment by JuliaDickey** [comment]
It was behind the button. Fixed it.
