### ISSUE TITLE
Update CTA Text

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#41]
I went through all of these and made a couple text edits, as well as added text for those that are missing it. I like the large text + small text but I noticed that some of them have really small text for the description. let's keep it consistent and do it like what you have on Our Story.

Please also check the links are redirecting correctly because I clicked on a volunteer link and it went to a the sponsor page. 

Final text:
- [x] Donate
BE A DONOR
Help us put kids into red sweaters and in the classroom. Every dollar makes a difference.
Button: DONATE

- [x] Blog - You have two different banners for this. Make sure they are the same (button is different on each  https://intense-spire-56347.herokuapp.com/pages/ourfocus and https://intense-spire-56347.herokuapp.com/events)
KEEP UP WITH US
Check out our blog to keep track of what's happening at Mungere and beyond. 
Button: EXPLORE THE BLOG 

- [x] Our Story
WHY EAST AFRICA?
It’s a long way from Portland to Tanzania. Read how our founder, Ashley Holmer, first saw the potential in a red sweater and explore our timeline to see how far we’ve come since 2005.
Button: SEE HOW IT ALL BEGAN

- [x] Our Focus
OUR FOCUS
Quality education, gender equality and responsible innovation. Learn how we are making an impact in Mungere Village.
Button: LEARN ABOUT OUR FOCUS

- [x] Sponsor
BECOME A SPONSOR
Create a unique relationship while changing a child's life. 
Button: LEARN ABOUT SPONSORSHIPS

- [x] Volunteer ( Please also check the link is going to the right page. It went to the wrong page when I clicked it)
VOLUNTEER WITH US
Volunteer your time in Tanzania or abroad and walk away with a new perspective. 
Button: EXPLORE VOLUNTEER OPPORTUNITIES

- [x] Newsletter
DON'T MISS A THING
Subscribe to our newsletter and stay up-to-date with the school and Red Sweater Project. 
Button: SUBSCRIBE

**Comment by JuliaDickey** [comment]
Hey Kelsey, 

Can you confirm which CTA style you like? You said you like the one on Our Story, but that one doesn't have a CTA on heroku. 

Thanks!
Julia

**Comment by JuliaDickey** [comment]
All CTA's are updated with new, resized images; correct links; consistent styles.

**Comment by kelseyfriedman** [comment]
This all looks great. A couple things

- [ ] Donate page and Our Story don't have banners. Let's just throw in two that aren't being used as much.  Unless this was intentional?
- [ ] I also was unable to access the Sponsor or Invest in a Cause pages so we need to confirm they have working CTAs once the pages work.

**Comment by JuliaDickey** [comment]
I left the CTA off of Donate, because we don't want someone to leave the Donate page to go somewhere else. That's the final destination. I added one to Our Story

**Comment by kelseyfriedman** [comment]
That makes sense to me re: not having a banner on donate. 

- [ ] There are two banners on the Our Story Page. Please remove the one between the story and the timeline and leave the one at the bottom (BTW I love the layout of that page!)

**Comment by JuliaDickey** [comment]
Yay! Done.
