### ISSUE TITLE
Update Our Focus Text

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#42]
QUALITY EDUCATION (let's add some new exciting info!)
- [x] Red Sweater Project's focus on quality education has set us apart since the beginning. Our success is not defined by the number of schools that we build, but by the effectiveness of our graduates as leaders in their communities. In 2013, Mungere students scored in the top quarter of schools in our region and second in the district. In 2016, the school graduated its first Form IV class. Every Mungere graduate passed their national exams, compared to only 27% nationally.  The Tanzania Ministry of Education has recognized Red Sweater Project as a successful school model that gets quick results, while investing in a long term vision.
- [x] Remove WHAT DOES THE FUTURE HOLD? section altogether. It kind of breaks up the flow of the 3 focuses and feels kind of unrelated to the Quality Education bullet. 

GENDER EQUALITY
- [x] This came from Jordan's team and we are okay with his edit: The first sentence “Boys don’t respect girls just because they’re told to,” followed by examples of girls earning the boys’ respect, doesn’t sit well with me. I understand that the message is empowering all genders, but it puts the onus on girls - the disempowered gender in society - to earn equal status. We can fix this by just deleting the first sentence so it starts with "Boys respect girls when they compete...".
- [x]  Delete the comma between "Whether it’s in math, or on the soccer pitch"
- [x]  Delete the comma after low and add one after floor “Girls who walked in the door with heads hung low, and eyes glued to the floor…” 
- [x] Remove comma: Read one teacher's account of student Tasiana's journey to becoming captain of the boys soccer team, and the impact she is having on her teammates.
- [ ] Needs to link to blog post once we create it (I tracked down the text and am waiting for the blog to be done to post) READ TASIANA'S STORY

RESPONSIBLE INNOVATION
- [x] Delete the comma: “Teaching and implementing creative solutions using sustainable technologies, and working with…” 

PART OF A BIGGER STORY
- [x] Capitalize: “Explore the Sustainable development goals…” → “Explore the Sustainable Development Goals”
- [x] The UN SDG link redirects back to the Our Focus page
- [x] I can hardly see the UN link (in fact I didn't see it at all until Jordan pointed it out and thought there was just a big empty space there). The link color is pretty close to the background color. What can we do? 

HOW WE’RE CREATING CHANGE 
- [x] add comma and change verb agreement: “Access to renewable energy resources, while teaching responsible consumption protect . . .” → “Access to renewable energy resources, while teaching responsible consumption, protects the environment and increases access to technology.”
- [x] All of these bullets have periods and the list in the section above does not. Seems like they both don't have complete sentences so maybe no periods? But we need to be consistent throughout the site on this.

**Comment by JuliaDickey** [comment]
I'm not seeing this line on the page:  Delete the comma between "Whether it’s in math, or on the soccer pitch"

The rest of the edits are done.

**Comment by kelseyfriedman** [comment]
@JuliaDickey it's the second sentence of the gender equality section. 

A couple new things to add:
- [ ] The change you made to the UN link now causes a double underline. When I hover it adds another underline above the white one. See screenshot
- [ ] There are a couple of broken images on this page. They are after Tasiana CTA and Partner With Us (see screenshot)


![brokenimage](https://cloud.githubusercontent.com/assets/3065594/23121561/f504ba4a-f771-11e6-95ea-d72b0843b9c4.png)
![underline](https://cloud.githubusercontent.com/assets/3065594/23121562/f50b56ac-f771-11e6-86ba-66f75276d6ff.png)

**Comment by JuliaDickey** [comment]
I'm adding the Tasiana link to a new issue since it's the only one left.

**Comment by kelseyfriedman** [comment]
@JuliaDickey  Did you push these changes? I'm not seeing the images fixed or the double underline fixed?

**Comment by JuliaDickey** [comment]
Yeah. I actually went back and changed this block. Let me know what you think.

**Comment by kelseyfriedman** [comment]
Love it! This page looks awesome! See my notes about images on issue #3
