### ISSUE TITLE
Hero images don't resize well for responsive

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#45]
I looked on my colleague's Nexus 5x (android) and the photos resize correctly on hers so it may just be a problem on iOS.

**Comment by JuliaDickey** [comment]
Try this now, and let me know how it works.

**Comment by kelseyfriedman** [comment]
Good except the FAQ page has no hero image anymore?

Also the events, sponsor and causes pages are all broken so I can't test those.
