### ISSUE TITLE
Donate sidebar is broken on mobile

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#49]
It's getting too narrow and cutting the text off. It should drop below the main content area

iPhone6 safari and Nexus5 Chrome

**Comment by JuliaDickey** [comment]
I removed this on mobile. I can drop it below, but I doubt people would see it. Thoughts?

**Comment by kelseyfriedman** [comment]
I'm fine with this
