### ISSUE TITLE
Sponsor page layouts not responsive on mobile

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#51]
Causes and students are not responsive on my phone. It's cutting off the sides instead of going down to a single column. works on Faye's Android)

iPhone6 safari

**Comment by JuliaDickey** [comment]
I checked this on my phone, and it worked (iphone 6)

**Comment by kelseyfriedman** [comment]
Sponsor page is broken so I can't re-test. Please give back to me when the page is fixed
