### ISSUE TITLE
Hero header text different on Android and iPhone

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#53]
Attaching screenshots to show you that Andoid (Nexus 5x) is displaying a very different font than my iPhone6.

![text_android](https://cloud.githubusercontent.com/assets/3065594/22973623/888ab742-f38f-11e6-9cbf-cef94920c1d3.png)
![text_ios](https://cloud.githubusercontent.com/assets/3065594/22973624/888c16be-f38f-11e6-8c46-b7e7e54f4007.png)

**Comment by JuliaDickey** [comment]
I checked this in an android simulator, and the correct font was loading. Cursive was the backup font if the phone didn't have internet access to the correct font. I changed it to a sans-serif, so at least it will fit better aesthetically if there's a poor signal.
