### ISSUE TITLE
Fix student bio links

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#55]
- [x] Check to make sure each page is using only a few font sizes

- [x] check for consistency of font size across site (e.g. all headers use the same, lists use the same, labels use the same, etc)

**Comment by JuliaDickey** [comment]
Done. Holler if you see anything I may have missed, but I swept through all pages, got rid of some extra styles and cleaned up some of the line-heights and sizes. I also added our blue as the link blue to replace the default and cleaned up the volunteer position lists. I reworded the link to view volunteer positions and to view student bios. It was pretty vague, and we don't want people thinking clicking the link will lead to an unwanted download. Holler if those are ok or need tweaking. They now read: " View position summary PDF online" and "View my full bio online"

**Comment by kelseyfriedman** [comment]
Oh I love love love what you did with the volunteer positions! I wasn't loving how it looked before but decided not to make it a thing, so I'm glad you agreed and gave it an upgrade! 

- [ ] Student bio links aren't working? 

Everything else looks great!

**Comment by JuliaDickey** [comment]
I fixed the bio links for the Students!

**Comment by kelseyfriedman** [comment]
Faustine and Amani's profile links aren't working. 

Also, why are the page titles on those so strange? Is that the name of the PDF? for example Emmanuel Hendry.pages?

I wonder if we need to rename those PDFs and upload them so they are all consistent. For example Emanuel Hendry Profile

**Comment by JuliaDickey** [comment]
I re-uploaded Faustine and Amani's profiles to the database, and they are working now. 

I'm not sure what you mean by page titles? Could you take a screen shot? I'm not seeing that in my browsers. The PDF titles are all consistent, unless they have been replaced by someone else in the admin dash. 
<img width="212" alt="screen shot 2017-03-27 at 7 59 40 am" src="https://cloud.githubusercontent.com/assets/19519395/24363015/5fb3e3d6-12c3-11e7-8ae6-aeaba6fdac0c.png">

**Comment by kelseyfriedman** [comment]
The titles on the tabs. 
Agness' says un7rbmdyvxfwimhcckya.pdf
Hamisi's says Haminisi Alhaji.pages
Faustine's says Faustine Amiri - NEED

Any way to control this? Also can we swap out with our favicon or is that not possible since they are hosted somewhere else? 
![screen shot 2017-03-28 at 10 57 50 am](https://cloud.githubusercontent.com/assets/3065594/24394666/81c60c28-13a5-11e7-8cfe-586c012d933d.png)

**Comment by JuliaDickey** [comment]
There is a way to do this, but I would have to manually rename the PDFs in Cloudinary, and manually update the links to students, which defeats the purpose of having it automated. They're aware of the glitch in being unable to customize the public_id, but it's super lame they haven't fixed it yet. I also can't change the favicon because these are being hosted on cloudinary, so it's outside of our site.

**Comment by kelseyfriedman** [comment]
Yeah I kinda figured. Okay well maybe in the future we can find a solution to this. It'll have to do for now. Really weird it's naming the PDFs differently than they are named on your computer though. I wonder where it's pulling that from? Closing this but let's keep this on our minds in the future.
