### ISSUE TITLE
Font rendering showing weird boxes in some places

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#56]
Jordan's team noticed some weird boxes appearing across the site. I have asked which browser/os they are using but I'm attaching screen shots so you can see (effect and difference). I will update the bug when I know the rest of the info. 

![rsp site preview - effect](https://cloud.githubusercontent.com/assets/3065594/23010030/5d981a34-f42a-11e6-8006-bcf9f15c52dd.PNG)
![rsp site preview - off difference](https://cloud.githubusercontent.com/assets/3065594/23010033/5e6ba75a-f42a-11e6-9670-4188cc2bae96.PNG)

**Comment by kelseyfriedman** [comment]
Okay he said it was  Chrome and Microsoft Edge.

UGH Edge.... WHY did they invent another new browser???

**Comment by JuliaDickey** [comment]
I added sans-serif as a backup, so if the font wont' load from the web site it will select a local font that it can render properly. I read up about this Microsoft bug, and it supposedly only affects Asian languages, y'know, like English.

**Comment by kelseyfriedman** [comment]
I'm having Jordan's tester take a look and see if it's still there.

**Comment by kelseyfriedman** [comment]
Jordan confirmed this is fixed. Closing
