### ISSUE TITLE
Move Invest in a Cause to Get Involved Menu

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#58]
Ashley's on board with making a new page. 

- [x] Create new page with this content titled "Invest in a Good Cause on Campus" but title it "Invest in a Cause" in the Get Involved menu
- [x] Intro text should say "There are several projects underway at the Mungere School that need the support of donors like you. Explore our projects below and support your favorite cause."
- [x] the dollar amounts over 500 need commas in them. (2,000 10,000 20,000 and 50,000)
- [x] add USD before the dollar amount on all causes. Suggested gift: USD $25
- [x] When a user clicks "Contribute" it takes them to the donate page with dollar amount filled in and the notes field filled in. The text for the notes field is as follows:
- I want to invest in Mungere athletes.
- I want to invest in school essentials.
- I want to invest in growing the garden.
- I want to invest in Mungere teachers.
- I want to invest in professional development.
- I want to invest in campus water.
- I want to invest in nutritious meals.
- I want to invest in solar energy.
- I want to invest in a new classroom.

**Comment by JuliaDickey** [comment]
I'm moving the donation messages to a new issue so I can reference them

**Comment by kelseyfriedman** [comment]
Page is broken so I cannot QA. Please fix and then reassign to me when you are done.
