### ISSUE TITLE
Move Red Sweater content to homepage

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#59]
Ashley's on board with this change. 
Since we are combining the pages, we have edited the text for the homepage. Please use this bug as the final definitive text for homepage and replace it all. 

- [x] Hero image with header text.  Use alternate text for intro.
Because of Red Sweater Project: An entire community of children is able to complete high school for the very first time.

**Upper section in white background includes intro and Red Sweater text**
- [x] Intro graph
Red Sweater Project offers high-quality middle and high school education for kids in rural East Africa. Wonder Woman has her cape and Zorro has his mask. In Tanzania, a school uniform is transformational. Putting on a red sweater means having the opportunity to learn and to better an entire community.
CHECK OUT THE SCHOOL CTA (please tighten up spacing above and below the button)

- [x] IT STARTS WITH A SWEATER
At the Mungere School, students learn creative problem solving and to use their education to invest in themselves, their families, their villages and the world. It's a ripple effect. And it starts with a red sweater.

COMMON THREADS
Red and blue colors, traditionally worn by the indigenous Masaai tribe, inspired our school uniform of red sweaters with blue skirts or pants. This design represents our commitment to enhance—not replace—tribal heritage. 

SO MUCH MORE THAN CLOTHING
Our integrated approach helps students to thrive. In addition to a well rounded education, our students receive medicine and health care, nutritious meals at school and a safe, supportive environment within the community.

**Lower section in blue includes Our Focus**
My only change is to the three distinct ways. I find the break in the sentence between the header and the smaller text a little jarring so I think we should just make the body text below each header a full sentence.
1. QUALITY EDUCATION
It’s not enough to build buildings: Our qualified teaching staff brings the classroom to life.
2. GENDER EQUALITY
This isn’t learned in a book. It’s cultivated by first-hand experience. 
3. RESPONSIBLE INNOVATION
We make sure our impact in the local and global community is a positive one.

{remove extra spacing before button}
LEARN MORE ABOUT OUR FOCUS

**Comment by JuliaDickey** [comment]
**It starts with a sweater:** Could we get a vertical image of a student in a sweater with their family in traditional clothing? I know we have one somewhere, and that would bring together these two paragraphs. 

Good call on separating the focus items from the supporting text. Much nicer.

**Comment by kelseyfriedman** [comment]
@JuliaDickey that's gonna be a tough one to get in the next week or two because we'd have to do a home visit and not sure if I can pull that off right now. We do need to do some home visits so if I can do it I will but if not.... 

I'm wondering if we should just do a nice photo of a kid in a red sweater? I think the big image of the family is a little too big- it really pushes the rest of the content pretty far down the page. I wonder if we should just do a smaller one of a red sweatered- student?

I'm gonna move this back to your In Progress since we need to get the photo swapped.
