### ISSUE TITLE
Add messages to Causes donations

### ISSUE THREAD

**Issue by JuliaDickey** [JuliaDickey/Red-Sweater-Project-Rails#61]
When a user clicks "Contribute" it takes them to the donate page with dollar amount filled in and the notes field filled in. The text for the notes field is as follows:
I want to invest in Mungere athletes.
I want to invest in school essentials.
I want to invest in growing the garden.
I want to invest in Mungere teachers.
I want to invest in professional development.
I want to invest in campus water.
I want to invest in nutritious meals.
I want to invest in solar energy.
I want to invest in a new classroom.

**Comment by JuliaDickey** [comment]
Sould you add this to the Project? I am not sure how. Thank you!

**Comment by JuliaDickey** [comment]
Done!

**Comment by kelseyfriedman** [comment]
Awesome! I love the way these worked out. I'll let you test functionality with the card with Ashley but I'm stoked on how this page came together.

The only thing I'm noticing is on the individual Invest pages, there is a big space between the header and the main body content. Can we tighten that up?

**Comment by JuliaDickey** [comment]
Yes, that was on my radar. Updated as of this morning.
