### ISSUE TITLE
On Android, homepage header text is cut off

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#64]
![screenshot_20170220-140749](https://cloud.githubusercontent.com/assets/3065594/23123371/1fc637b6-f779-11e6-87ca-c32d3b268677.png)

**Comment by JuliaDickey** [comment]
I'm not sure if this is still an issue. I don't have an android to reference. I think it's fixed.

**Comment by kelseyfriedman** [comment]
Faye got her phone stolen this weekend in Moshi so I don't have an Android anymore. Do you have any friends with an Android that can look at this for you?

I think she's getting a new one Friday so hopefully in the future I can QA Android again but I can't right now :(

**Comment by kelseyfriedman** [comment]
This doesn't seem to be an issue anymore. Closing
