### ISSUE TITLE
Update homepage header text

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#65]
The first is our preference but if it's too long you can do the second. 

A generation of African children are changing lives through education.
East African children are changing lives through education.

**Comment by JuliaDickey** [comment]
I still don't think this is right. They only have education because of red sweater project, and we have no proof that the children are changing lives. The education changes lives. We need this line to summarize what Red Sweater Project does. I can ask my writers to take a stab at it if you like.

**Comment by kelseyfriedman** [comment]
@JuliaDickey  Sure, why don't you have them give it a shot. I spoke to Ashley and she argues that we are changing lives and that's proven. Some of our pre-form Vs are now going to med school, their families have saved hundreds of dollars on their education, etc etc.

We're happy to look at other options if you guys come up with something.

**Comment by kelseyfriedman** [comment]
Sona's suggestion was 
Kids in East Africa Have Access To a High-Quality Education. 

Please discuss with Ashley in the in person meeting. I think the three of you can come to an agreement and I'll be happy with whatever.

**Comment by kelseyfriedman** [comment]
I'll close this bug but please make sure Ashley signs off on this homepage text in your meeting. Thanks
