### ISSUE TITLE
Link to Tasiana blog

### ISSUE THREAD

**Issue by JuliaDickey** [JuliaDickey/Red-Sweater-Project-Rails#66]
From Our Focus Page:
Needs to link to blog post once we create it (I tracked down the text and am waiting for the blog to be done to post) READ TASIANA'S STORY

**Comment by kelseyfriedman** [comment]
Waiting on issue #37 to be complete

**Comment by JuliaDickey** [comment]
Added the link.

**Comment by kelseyfriedman** [comment]
It's still just linking back to /ourfocus for me?

**Comment by JuliaDickey** [comment]
I just checked this, and it links to blog/tasiana-kicks.
