### ISSUE TITLE
Updates on Volunteer Page

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#69]
- [x] Looks like a break is missing between the graphs on the intro 
- [x] Also, will the photo Ashley found (attached) work for the hero or is it too small? I think it would be better to show a volunteer with RSP kids rather than villagers. If not, I like this photo, but it's less "Red Sweatery" you know? 
![volunteer teaching photo](https://cloud.githubusercontent.com/assets/3065594/23354801/e1be7170-fce3-11e6-857d-feb1f7ac9263.jpg)

**Comment by JuliaDickey** [comment]
I like this image better. It's a little lo res, but not bad. What do you think?

**Comment by kelseyfriedman** [comment]
Way better, let's use it
