### ISSUE TITLE
Build Our Story/Timeline page

### ISSUE THREAD

**Issue by JuliaDickey** [JuliaDickey/Red-Sweater-Project-Rails#7]

**Comment by JuliaDickey** [comment]
I've set up the page, and dropped in the content from Kristi. I can reflow if there are copy edits. Also, do we have any images from Ashley in the founding days of the school? Playing soccer, etc? That might be nice.

**Comment by kelseyfriedman** [comment]
Will check on photos. Assigning this to myself.

**Comment by kelseyfriedman** [comment]
Julia, I have uploaded 6 photos to the Dropbox to choose from for the our Story page. I think the one of Ashley with all the kids around her is the nicest choice for the Hero image if it works and is large enough. The others could be used on the page as well if you like them.

**Comment by JuliaDickey** [comment]
I love this photo. It's a bit blurry, but it's old so I think it works. What do you think?

**Comment by kelseyfriedman** [comment]
Looks great and Ashley also loves it! It took a while to load on my page though - how big is the file?

**Comment by JuliaDickey** [comment]
It's 274kb. I hesitated to make this one smaller since it's already so
fuzzy. I can drop it down and see how low we can go :)
