### ISSUE TITLE
Bio text on mobile too narrow

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#70]
The responsive on the bios on mobile is causing them to get really narrow. Anything we can do here? 
![img_0036](https://cloud.githubusercontent.com/assets/3065594/23366670/9d4ad4ae-fd18-11e6-9d1d-ca4f154b4f5a.PNG)

**Comment by JuliaDickey** [comment]
Yup. Hid images on mobile.
