### ISSUE TITLE
Update Irrigation Photo - Invest in a Cause

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#71]
@JuliaDickey I took this photo in the garden when I first got here and just found it again. I think it's better than the one we have in irrigation system since it just shows people rather than water (and isn't even in our garden). 

What do you think about using this instead? Your call if it looks better or not. 
![img_3397](https://cloud.githubusercontent.com/assets/3065594/23449779/fc3244ec-fe68-11e6-9fbc-06cdbad1d9cf.JPG)

**Comment by JuliaDickey** [comment]
It kinda just looks muddy, and like we already have a watering system in place. I think we should just stick to the photo we have. Is that cool?

**Comment by kelseyfriedman** [comment]
Yep, totally fine.
