### ISSUE TITLE
Edit Newsletter thank you text

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#72]
It's not monthly and we don't want to commit to any time frame so let's just remove that and say.

Mambo!

Thank you for signing up for the Red Sweater Project newsletter. You can expect to occasionally receive brief, exciting emails with updates from the Mungere School and beyond. 

Asante sana!
Red Sweater Project

**Comment by JuliaDickey** [comment]
I think this might be a phase 2 thing, if needed. It doesn't seem really necessary. Are you cool with us not adding the email?

**Comment by kelseyfriedman** [comment]
I'm a little confused, are you saying there is no email at all or you don't want to edit the text? I thought the email was already built and we were just editing text? I tested this and didn't get an email confirmation so I think that's what you are saying. I think it's pretty important to get some kind of confirmation it worked. If you don't want to do an email, then maybe we need to have a confirmation in the modal that says thank you? It feels incomplete to me the way it's set up. I questioned if it worked when I clicked "subscribe."

This is less of a priority than the other bugs, but in order to call MailChimp complete, I think we need a confirmation of some sort. It seems quite easy. I found this article with some info https://blog.mailchimp.com/sending-different-welcome-emails-based-on-signup-source/ 
 
It seems we just need to turn on the Welcome Email from the settings page and then can customize the text? It also seems like we should turn on the Unsubscribe confirmation email option? https://us8.admin.mailchimp.com/lists/settings/defaults?id=517753

Do you want me to try this and see if it works?

**Comment by JuliaDickey** [comment]
See email note.

**Comment by kelseyfriedman** [comment]
Fine passing this off to Jordan but would need to know what you need from him since I don't exactly know what an automation is?

**Comment by JuliaDickey** [comment]
This is now done. It was easier just creating one to begin with, and he can edit it with the instructions I sent. Let me know if this works for you.

**Comment by kelseyfriedman** [comment]
Works for me! I do want to test the process though and I can't until the site is back up so leaving this bug open. 

I've sent the text to Jordan and asked for his edits. Depending on when I hear back, I can edit it myself or might have to have you do it if I'm in Rwanda. He's working on some major board report stuff right now so I'd rather us just do the edits. I'll let you know when I hear back.

**Comment by kelseyfriedman** [comment]
So I tested the email and I didn't get the two part thing - just the second email that said Mambo. Shouldn't I have gotten one that asked me to confirm my email address first? Did you get it when you tested? 

Jordan responded that he likes the text. He suggested we add some English to explain the Swahili. I have asked Ashley to make the final call and copied you so you know if we need to edit that text. 

I am giving this bug back to you.

**Comment by JuliaDickey** [comment]
I created a confirm email template, but couldn't figure out how to add it to the Automation sequence. Since the Welcome email has an unsubscribe link I think this works as is, but it's something we can add in if you think it's needed. 

Cool. I'll add updating/approving the text to the docket for tonight.

**Comment by JuliaDickey** [comment]
Approved!

**Comment by kelseyfriedman** [comment]
No I don't think we need it at all. I agree the unsubscribe is enough. Thanks!
