### ISSUE TITLE
Contact page is broken

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#73]
When I go to it I can't see anything on the page.

**Comment by JuliaDickey** [comment]
Fixed.

**Comment by kelseyfriedman** [comment]
Something happened with the padding on mobile. The CTA banner is being cut off and the left side lost it's padding. 
![img_5569](https://cloud.githubusercontent.com/assets/3065594/23949259/ac6514f0-0997-11e7-9559-445323bde5fa.PNG)

**Comment by JuliaDickey** [comment]
Fixed.
