### ISSUE TITLE
Make Ashley's last copy changes

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#75]
Not sure if you are waiting to discuss with her in person but these changes need to be made still so I'm making an issue. Seems like a good conversation to discuss personally cause there are some sticky subjects in here. Do you mind asking her when you meet?

https://mail.google.com/mail/u/0/#inbox/15ab53b94aaf390f

**Comment by JuliaDickey** [comment]
Sona is reviewing these, and will have recommendations ready for me by end of day Wednesday.

**Comment by kelseyfriedman** [comment]
I pasted Sona's suggestion into Ashley's doc with comments and asked her to review. I like Sona's edits so if Ashley says go ahead, please just make the changes

**Comment by JuliaDickey** [comment]
I made Sona's edits since Ashley confirmed. Ashley asked me to rewrite the section about the burden of educating girls. I can pass it back to Sona, or do you want to take a crack at it?

**Comment by kelseyfriedman** [comment]
I just did a rewrite and asked Ash for feedback in her doc. 

I also left her a separate comment because Sona you and I decided that the https://www.malala.org/brookings-report/the-worlds-best-investment-girls-education report didn't substantiate "more than any other cause" and I suggested a rewrite for that that removed that claim. I see that hasn't been made on the site yet - but I asked Ashley if she had solid proof for that because in her comments in her own doc she said "we should never remove that line because we can back it up with stats"

Giving this back to you In Progress until we lock down these last two issues.

**Comment by kelseyfriedman** [comment]
I've answered your Questions in Sona's document.... I think? Let me know if you need anything else here or if we can wrap this up now

**Comment by JuliaDickey** [comment]
Yup. I think that covers it. I sent you an email about the bios page. That might need to be a separate ticket.

**Comment by kelseyfriedman** [comment]
@JuliaDickey marking this as complete. 

I saw you made the changes in Sona's doc so I'm hoping this means all of Ashley's edits (save for the bios) are DONE DONE. I didn't resolve the new comments from your meeting because you were the one doing that before, but feel free if you are ready. I did resolve the ones related to this bug directly.
