### ISSUE TITLE
Donate page sidebar

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#77]
I'm afraid that people will think that dollar amount gets all of those things rather than just one of those things. What do you think? Would bullets help? Do we need to say OR? Does it matter and I should just shut up?

**Comment by JuliaDickey** [comment]
Asking Sona. I'm too inside it to know for sure.

**Comment by JuliaDickey** [comment]
Sona agreed. Here's her suggestion:
Hmmm. To me it looks like it's saying the donation would cover all of the things on the list - even though that seems crazy when you're talking about $25, $50, etc.

I don't think bullets will solve that problem. And you probably don't want to repeat "or" over and over again. 

Could you add a subhead that says something like:

Here are just a few of the possibilities at each donation level:

__________________________________
I've made this update. Holler if that sounds ok.

**Comment by kelseyfriedman** [comment]
Good for me!
