### ISSUE TITLE
Share Gooogle Analytics with kelsey

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#78]
When we go live, please share the analytics with me as I want to start tracking views and visits from FB etc.

**Comment by JuliaDickey** [comment]
Done. You should have received an email. Let me know if it's not in your gmail.

**Comment by kelseyfriedman** [comment]
@JuliaDickey so is the data we ares seeing for the heroku site or the live site rsp.org?

**Comment by JuliaDickey** [comment]
It's for redsweaterproject.org, which will point to the new site when we
launch and we can still see the old data for comparison.

**Comment by kelseyfriedman** [comment]
@JuliaDickey cool! I was a little confused because there was a fair amount of visits on GA and I was surprised that people would be visiting it so much - but maybe it's just you and me and Ashley :)
