### ISSUE TITLE
CTA Button text doesn't fit

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#83]
https://intense-spire-56347.herokuapp.com/ourstory
https://intense-spire-56347.herokuapp.com/news
volunteer CTA text is outside of button

**Comment by JuliaDickey** [comment]
Any chance we could shorten this one up? It won't fit on mobile. "Learn more" or "Explore Volunteering"

**Comment by kelseyfriedman** [comment]
Let's do Explore Volunteering... or what about "Volunteer With Us"? 

You choose

**Comment by JuliaDickey** [comment]
Explore Volunteering feels like it's less of a commitment, so I went with that. Done.
