### ISSUE TITLE
Text edits regarding use of "The"

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#84]
Hi Julia, 

Sorry to add this to your plate. In Sona's style sheet, she noted we need to be consistent with Red Sweater Project and Mungere School. I asked Ashley for final say and she agreed it's 
Red Sweater Project
Mungere School

There are cases where we might say "the Mungere School" like you might say "the University of Oregon," but it should never be capitalized as a formal part of the name. 

That being said... I swept through every page to catch inconsistencies. I left "the Mungere School" in some places where it made sense, but removed "the" from Red Sweater Project pretty much everywhere. POLE SANA!

If you see [ ] around something below it means please remove it. Thanks. 

Homepage:

- [x] established by [the] Red Sweater Project.

- [x] newsletter CTA Subscribe to our newsletter and stay up to date with [the] Mungere School 

MailChimp modal

- [x] Subscribe to our newsletter and stay up to date with [the] Mungere School and Red Sweater Project.

Our Story 

- [x] That’s why Ashley founded [the] Red Sweater Project in 2011, with the goal of putting as many kids in school as possible.

Timeline

- [x] September 2012 Beginning with an English immersion program, the Mungere [Secondary] School

- [x] April-June 2011 The village donates 15 acres of land on which to build the Mungere [Secondary] School

- [x] January 2011 Ashley Holmer and fellow passionate volunteers form [the] Red Sweater Project

The School

- [x] [The] Mungere School is the first [middle and] high school available to kids in the rural community of Mungere, Tanzania.

- [x] When completed, [The] Mungere School will serve over 300 students each year.

- [x] Reinvests in [The] Mungere School to offset operational costs.

- [x] [The] Mungere School is located 3 hours from Kilimanjaro airport

FAQ

- [x] Each year, around 200 students apply for one of the 40 spots at [The] Mungere School.
WHAT CAREER OPPORTUNITIES DO STUDENTS HAVE FOLLOWING COMPLETION OF THEIR HIGH SCHOOL STUDIES AT [THE] MUNGERE SCHOOL?

- [x] Undoubtedly. With more than 125 students enrolled in [The] Mungere School, 

- [x] The opportunity to enroll in [The] Mungere School provides students with a sense of possibility and the education and skills to succeed in a 21st-century world.

- [x] From engineering to computer information technology to sustainable farming, [The] Mungere School utilizes a broad range of skills 

Blog
I didn't want to make changes to the database at the same time you are so here are the blog edits. I can do them if you don't have time but let me know when the right time to do so is. 

https://intense-spire-56347.herokuapp.com/blog/tasiana-kicks
- [x] Tasiana Kabuka is a 16-year-old Form IV student here at [The] Mungere School.

https://intense-spire-56347.herokuapp.com/blog/first-day-of-school

- [x] As part of a recent writing class, two teenagers put pen to paper to describe their first few weeks at [The] Mungere School and how they began to learn English.

- [x] [The] Mungere School offers a revolutionary approach to this problem—all new students go through an English immersion program conducted over several months by native speakers.

https://intense-spire-56347.herokuapp.com/blog/the-portland-timbers-find-a-new-rival-in-the-mungere-red-rhinos

- [x] Over the summer, the former mascot and Director of Love and Celebration visited [The] Mungere School in rural Mto wa Mbu. 

- [x] [The] Mungere School, in northern Tanzania, was started in 2012 by ardent Timbers fan Ashley Holmer. 

https://intense-spire-56347.herokuapp.com/blog/the-mungere-garden-thrives-after-a-summer-makeover
- [x] The summer break saw the transformation of [The - lowercase the] Mungere School garden—and now it has just had its first harvest.

- [x] Over the four-week school break in June, [The] Mungere School welcomed "Timber" Jim

https://intense-spire-56347.herokuapp.com/blog/form-iv-students-celebrate-as-they-finish-their-national-exams

- [x] These students come from such poor families and they would never have been able to go to secondary school without [the] Red Sweater Project. 

- [x] [The] Mungere School is hoping to begin its Form V program with as many students as possible from the current Form IV.

https://intense-spire-56347.herokuapp.com/blog/congratulations-to-mungere-school-s-first-graduating-form-iv-class

- [x] Much of the graduation service paid tribute to how vital the community both at home and across the globe—has been in supporting [the] Red Sweater Project, set up by Ashley Holmer.

- [x] Before [the] Red Sweater Project, they were destined to a life without education because their parents were not in a position to send them to the prohibitively expensive government schools.

- [x] He said: “Working together we achieve greatness and this is exactly what has happened at Mungere [Secondary] School. 

- [x] The 29 Form IV students were the first to start when Mungere [Secondary] School opened its doors in 2012. 

- [x] “If Mungere [Secondary] School was not here—like many of the girls in Form IV—I would have been married with children by now. 

Volunteer

- [x] Red Sweater Project partners with numerous volunteer groups each year who travel to Tanzania to complete projects at [the] Mungere School.

Invest in a Cause

- [x] There are several projects underway at [the] Mungere School that need the support of donors like you. Explore our projects below and support your favorite cause.

Get Creative

- [x] Whether it's 26.2 miles or .05k, a race is a great way to raise funds and support for the work happening at [the] Mungere School. 

Donate

- [x] · Outfit 5 students in their [Red Sweater- add Project at the end] uniform.

**Comment by JuliaDickey** [comment]
Thank you for this! I made all of the changed except those in the blog content. You can go ahead and make edits to the blogs. If I need to pull down the database to make changes I will send out an email first, but I don't think that's necessary at this point. Heads up: Ashley is jumping in too. You might want to plan how edits will be tracked with her. She wants to update job posts. 

The only tricky edit is the last one: Outfit 5 students in their Red Sweater Project uniform. The uniform is for Mungere School, not RSP. Should we say "Outfit 5 students in new school uniforms"? I think it's pretty obvious at this point that includes a red sweater. What are your thoughts?

**Comment by kelseyfriedman** [comment]
I'll make the blog changes tomorrow. Let's do "Outfit 5 students in new school uniforms"

**Comment by kelseyfriedman** [comment]
Looks like I missed one on the homepage
- [ ] For these students, putting on a red sweater means access to a high-quality high school education at [the] Mungere School,

**Comment by kelseyfriedman** [comment]
Looks like one got missed on The School
- [ ] [The] Mungere School is the first high school available to kids in the rural community of Mungere, Tanzania.

Blog is updated!

**Comment by JuliaDickey** [comment]
Thanks for updating the blog! That last [The] from The School page is gone. Done!

**Comment by kelseyfriedman** [comment]
Found one more today on the individual sponsor pages

Your tax-deductible gift supports HAMISI ALHAJI at [The] Mungere School, helping them complete their high school education as well as providing hands-on classes in organic agriculture and business.

**Comment by JuliaDickey** [comment]
Good catch! Got it.
