### ISSUE TITLE
Change or remove photo on Our Focus

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#85]
I just noticed we are using the same photo of the running team on Our Focus and as the hero on the blog.

I'm not sure we really need a photo in that spot on Our Focus, but if you do want to keep one, this image doesn't quite align with Quality Education since it's sports. I'd say we should either replace the Our Focus photo with one of kids in the classroom - there are tons of those- or just remove it altogether and only have the Tasiana photo on that page.

**Comment by JuliaDickey** [comment]
Removed it.
