### ISSUE TITLE
Icons on Homepage

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#86]
I see these are gone. I know Ashley wasn't crazy about them. Did you discuss in the meeting? 

If those were removed intentionally, I think we need to do something more stylized for the three text blocks. They look small and out of place on their own and there is a lot of white space surrounding them now. 

However, with the new content on the homepage, I think we could remove those altogether. I think you put them there because at the time we needed more visuals on the homepage, but the sentence above it says all the same stuff so it feels somewhat redundant and also competes with the three focuses below.

**Comment by JuliaDickey** [comment]
I went ahead and removed them.

**Comment by kelseyfriedman** [comment]
There's a lot of white space now between those two sections - partially because there is padding at the bottom of once section and the top of the other and partially because the colors of the two sections are so close that it all just looks white even though it's not. Can you reduce some of that padding ?
![screen shot 2017-03-28 at 10 42 01 am](https://cloud.githubusercontent.com/assets/3065594/24394232/d7b8c0fa-13a3-11e7-9e1f-d53aa39e0229.png)

**Comment by JuliaDickey** [comment]
Good eye. This is revised.

**Comment by kelseyfriedman** [comment]
This still looks really spaced out to me? Maybe you did it and it hasn't updated on my machine. I wonder if it's a caching issue? 

If you look at the padding before "It starts with a sweater" it seems a lot tighter than the padding above "A Clear Focus." If the margin at the bottom of the sweater section and the top of the clear focus was less, I think this issue would go away. 

Maybe you did it and it hasn't updated on my machine? I wonder if it's a caching issue?

**Comment by JuliaDickey** [comment]
Excellent eye! Thank you!

There was still some lingering margin, and a random br tag in there. Both are removed, and it matches the spacing above.
